### ISSUE TITLE
Using futures with mcMap

### ISSUE THREAD

**Issue by HenrikBengtsson** [statcompute/statcompute#1]
Hi WenSui,

I saw your blog post https://statcompute.wordpress.com/2018/09/03/playing-map-and-reduce-in-r-by-group-calculation/.  Unfortunately, unless I missed something, I don't think using a future as in:

    ft <- future({split(iris, iris$Species)})
    mcMap(function(i) with(value(ft)[[i]], ...))

will do you any good.  You create a future

    ft <- future({split(iris, iris$Species)})

but under the default future setup, which is plan(sequential), it will be resolve immediately in the main R process, so you could equally well do:

    ft <- future({split(iris, iris$Species)})
    chunks <- value(ft)
    mcMap(function(i) with(chunks[[i]], ...))

If you use parallel futures, e.g. ~~`plan(multisession)`~~ `plan(multicore)`, then due to the forked processing by `mcMap()`, you would actually forcing each workers (forked child process) to resolve that future when they each call `value(ft)`.  So with four workers, you would in that case do four times the work on the CPU than if you do:

    chunks <- split(iris, iris$Species)
    mcMap(function(i) with(chunks[[i]], ...))

So, I don't think futures help here.

FYI, in [future.apply](https://github.com/HenrikBengtsson/future.apply) (available on CRAN) there's a `future_Map()`.  To replicate `mcMap()`, you can use:

    library(future.apply)
    plan(multicore)

    chunks <- split(iris, iris$Species)
    future_Map(function(i) with(chunks[[i]], ...))

and if you're on Windows, you can use `plan(multisession)`.  On an ad-hoc cluster, you can use `plan(cluster, workers = c("machine1", "machine2", "machine3"))`, on a HPC cluster you can use `plan(batchtools_sge)`, and so on.

Cheers

PS. Couldn't find your email address anywhere.

**Comment by statcompute** [comment]
First of all, thank you so much for reading my blog, Henrik
You are absolutely correct that, from the efficiency standpoint, the future
won't do any good to speed up the computation. There is no doubt about that
and we are perfectly on the same page. It is very obvious in the benchmark.
However, if you read the post before this one, you might notice that the
point of using future in a setting with large datasets is trying to avoid
saving / storing large data.frame in the memory. The future will be only
resolved within the function and gone after used. Therefore, the data
represented by the future won't be even in the globalenv. In this regard,
the use of future has its value.

Once again, truly appreciate your insight and wish you a happy weekend!

Sincerely
wensui

**Comment by statcompute** [comment]
by the way, the future.apply seems interesting that I will take a look later.
if you don't mind, let's connect on linkedin and maybe we can discuss
something more technically intriguing.
thanks.

**Comment by HenrikBengtsson** [comment]
> the point of using future in a setting with large datasets is trying to avoid saving / storing large data.frame in the memory. **The future will be only resolved within the function and gone after used.** Therefore, the data represented by the future won't be even in the globalenv. In this regard, the use of future has its value.

Actually not. All futures are resolved _eagerly_, i.e. immediately.  How and _where_ is decided by the `plan()`.  If you want lazy evaluation you need to use `lazy = TRUE`;
```r
ft <- future({ split(iris, iris$Species) }, lazy = TRUE)
```
This will prevent evaluation of the future expression until you call `value(ft)`.  However, ...

> **the point of using future in a setting with large datasets is trying to avoid saving / storing large data.frame in the memory**. The future will be only resolved within the function and gone after used. Therefore, the data represented by the future won't be even in the globalenv. In this regard, the use of future has its value.

You will _not_ save an memory/RAM this way.

If you use the default `plan(sequential)` with the default `lazy = FALSE` (as in your post), then `split()` is resolved in the main R session and all forked workers will use that shared-memory object.  You effectively achieves nothing but sparing yourself a `chunks` object in the main R session (replaced by a `ft` object).  So, I'd argue it's better do use:
```r
chunks <- split(iris, iris$Species)
res <- mcMap(function(i) with(chunks[[i]], ...))
rm(chunks)
```

If you'd use the default `plan(sequential)` with the `lazy = TRUE`, then `split()` is evaluated/resolved `mc.cores` times - once per worker.  This means that each worker will that allocate memory seperately resulting in `mc.cores`-times more memory/RAM allocations on the machine.

Also, I recommend that don't you pass unresolved futures to parallel processes - they are designed to be interactive with in/by the process where they were created.  There might be some support for this in the future, but right now it's safest to not do it.

**Comment by statcompute** [comment]
Very good point about the lazy. Thanks for pointing out.
I will revisit it.
Appreciate your insight
